/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as EmbedMemoIdRouteImport } from './routes/embed/$memoId'
import { Route as SitePlaygroundIndexRouteImport } from './routes/_site/playground/index'
import { Route as SiteDocsIndexRouteImport } from './routes/_site/docs/index'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_site/route.lazy').then((d) => d.Route))
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any).lazy(() => import('./routes/_site/index.lazy').then((d) => d.Route))
const EmbedMemoIdRoute = EmbedMemoIdRouteImport.update({
  id: '/embed/$memoId',
  path: '/embed/$memoId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/embed/$memoId.lazy').then((d) => d.Route))
const SitePlaygroundIndexRoute = SitePlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => SiteRouteRoute,
} as any).lazy(() =>
  import('./routes/_site/playground/index.lazy').then((d) => d.Route),
)
const SiteDocsIndexRoute = SiteDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => SiteRouteRoute,
} as any).lazy(() =>
  import('./routes/_site/docs/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/$': typeof SplatRoute
  '/embed/$memoId': typeof EmbedMemoIdRoute
  '/docs/': typeof SiteDocsIndexRoute
  '/playground/': typeof SitePlaygroundIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/embed/$memoId': typeof EmbedMemoIdRoute
  '/': typeof SiteIndexRoute
  '/docs': typeof SiteDocsIndexRoute
  '/playground': typeof SitePlaygroundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/embed/$memoId': typeof EmbedMemoIdRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/docs/': typeof SiteDocsIndexRoute
  '/_site/playground/': typeof SitePlaygroundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/embed/$memoId' | '/docs/' | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/embed/$memoId' | '/' | '/docs' | '/playground'
  id:
    | '__root__'
    | '/_site'
    | '/$'
    | '/embed/$memoId'
    | '/_site/'
    | '/_site/docs/'
    | '/_site/playground/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  EmbedMemoIdRoute: typeof EmbedMemoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/embed/$memoId': {
      id: '/embed/$memoId'
      path: '/embed/$memoId'
      fullPath: '/embed/$memoId'
      preLoaderRoute: typeof EmbedMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/playground/': {
      id: '/_site/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof SitePlaygroundIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_site/docs/': {
      id: '/_site/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof SiteDocsIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
  }
}

interface SiteRouteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteDocsIndexRoute: typeof SiteDocsIndexRoute
  SitePlaygroundIndexRoute: typeof SitePlaygroundIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteDocsIndexRoute: SiteDocsIndexRoute,
  SitePlaygroundIndexRoute: SitePlaygroundIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRouteRoute: SiteRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  EmbedMemoIdRoute: EmbedMemoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
