/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as EmbedMemoIdRouteImport } from './routes/embed/$memoId'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedMemoIdRoute = EmbedMemoIdRouteImport.update({
  id: '/embed/$memoId',
  path: '/embed/$memoId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/embed/$memoId': typeof EmbedMemoIdRoute
  '/docs/': typeof DocsIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/embed/$memoId': typeof EmbedMemoIdRoute
  '/docs': typeof DocsIndexRoute
  '/playground': typeof PlaygroundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/embed/$memoId': typeof EmbedMemoIdRoute
  '/docs/': typeof DocsIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/i18n' | '/embed/$memoId' | '/docs/' | '/playground/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/i18n' | '/embed/$memoId' | '/docs' | '/playground'
  id:
    | '__root__'
    | '/'
    | '/demo/i18n'
    | '/embed/$memoId'
    | '/docs/'
    | '/playground/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoI18nRoute: typeof DemoI18nRoute
  EmbedMemoIdRoute: typeof EmbedMemoIdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$memoId': {
      id: '/embed/$memoId'
      path: '/embed/$memoId'
      fullPath: '/embed/$memoId'
      preLoaderRoute: typeof EmbedMemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoI18nRoute: DemoI18nRoute,
  EmbedMemoIdRoute: EmbedMemoIdRoute,
  DocsIndexRoute: DocsIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
